// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjv5nvmMqyuuW059XIbXZ95ZBEUKh1zU8',
    appId: '1:1094736290577:web:a4e5b2f298d90a198d22b0',
    messagingSenderId: '1094736290577',
    projectId: 'chatapp-524cb',
    authDomain: 'chatapp-524cb.firebaseapp.com',
    storageBucket: 'chatapp-524cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfuzQHJOSdnlOfBFdc4utmTlqBz-2I7N8',
    appId: '1:1094736290577:android:cd2dbaf1cede2a578d22b0',
    messagingSenderId: '1094736290577',
    projectId: 'chatapp-524cb',
    storageBucket: 'chatapp-524cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu0RcRXFqpqmTQJnWRSIy1XKbaHgq2Foo',
    appId: '1:1094736290577:ios:c3d726be97f562758d22b0',
    messagingSenderId: '1094736290577',
    projectId: 'chatapp-524cb',
    storageBucket: 'chatapp-524cb.appspot.com',
    iosBundleId: 'com.example.webAppAssign',
  );
}
